server:
  port: 7201
spring:
  application:
    name: hangyiyun
  redis:
    database: 0
    host: 8.129.18.200
    port: 6379
    password: "@Shsr_1320_@"
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://8.129.18.200:7101/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#显示日志
logging:
  level:
    com.hangyiyun.hangyiyun.mapper: debug
