---
server:
  port: 7101
spring:
  profiles: peer1
  application:
    name: buyerbackground-server-cluster
eureka:
  instance:
    hostname: peer1
  client:
    # registerWithEureka: true
    # fetchRegistry: true
    serviceUrl:
      defaultZone: http://8.129.18.200:7102/eureka/
---
server:
  port: 7102
spring:
  profiles: peer2
  application:
    name: buyerbackground-server-cluster
eureka:
  instance:
    hostname: peer2
  client:
    # registerWithEureka: true
    # fetchRegistry: true
    serviceUrl:
      defaultZone: http://8.129.18.200:7101/eureka/
