#---
server:
  port: 7101
spring:
  application:
    name: buyerbackground-server-cluster
eureka:
  instance:
    hostname: 8.129.18.200
#    client:
    #registerWithEureka: true
    #fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://127.0.0.1:7102/eureka/
#---
#server:
#  port: 7102
#spring:
#  profiles: peer2
#  application:
#    name: buyerbackground-server-cluster
#eureka:
#  instance:
#    hostname: 8.129.18.200
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://127.0.0.1:7101/eureka/
