server:
  port: 7501
spring:
  application:
    name: gateway
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
eureka:
  client:
    serviceUrl:
      defaultZone: http://8.129.18.200:7101/eureka/
